services:
  mariadb:
    image: bitnami/mariadb:latest
    container_name: custom-mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=rootpassword
      - MARIADB_DATABASE=moodle_db
      - MARIADB_USER=moodle_user
      - MARIADB_PASSWORD=moodlepass
    volumes:
      - mariadb_data:/bitnami/mariadb

  moodle:
    image: bitnami/moodle:latest
    container_name: custom-moodle
    ports:
      - "8080:8080"
    environment:
      - MOODLE_DATABASE_HOST=custom-mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=moodle_user
      - MOODLE_DATABASE_NAME=moodle_db
      - MOODLE_DATABASE_PASSWORD=moodlepass
    volumes:
      - ./moodle:/bitnami/moodle
      - ./moodledata:/bitnami/moodledata
    depends_on:
      - mariadb

volumes:
  mariadb_data:

